#!/bin/bash

function exit_if_error {
    local last_exit_code=$?
    if [ $last_exit_code -ne 0 ]; then
        exit $last_exit_code
    fi
}

DOCKER_IMAGE_NAME="sicei-${GIT_BRANCH}:1.0.0-${BUILD_NUMBER}"

npm install; exit_if_error

npm test; exit_if_error

docker image build . -t ${DOCKER_IMAGE_NAME}; exit_if_error
